## Python - Fundamentos para a Análise de Dados

### Cap 08 - Módulos Python para Análise de Dados - NumPy

Documentação do [NumPy](https://numpy.org/).

In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

### Criando Arrays

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [4]:
# Criando um array a partir de uma lista
vetor1 = np.array([0,1,2,3,4,5,6,7,8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
type(vetor1)

numpy.ndarray

ndarray -> é um objeto de recipiente multidimensional

In [7]:
#Utilizando métodos do array numpy
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [9]:
#Imprimindo objeto do vetor
vetor1[0]

0

In [10]:
#Alterando um elemento
vetor1[0]=100

In [11]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [12]:
#Não é possível incluir elementos de tipos diferentes no array
vetor1[0]='Oii'

ValueError: invalid literal for int() with base 10: 'Oii'

In [13]:
#Verificando o formato do array : unidimensional
vetor1.shape

(9,)

### Funções NumPy

A função **arange** cria um vetor contendo uma progressão aritmética a partir de um intervalor - start, stop, step.

**np.arange(start, stop, step)**

In [14]:
vetor2 = np.arange(0., 4.5, .5)

In [15]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [16]:
type(vetor2)

numpy.ndarray

In [17]:
#Formato do array
np.shape(vetor2)

(9,)

In [18]:
vetor2.dtype

dtype('float64')

In [19]:
x = np.arange(1,10,0.25)

In [20]:
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


**zeros**: Monta um array com um determinado número de zeros.

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**eye**: Retorna 1 nas posições em diagonal e 0 no restante do array.

In [22]:
z = np.eye(5)

In [23]:
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**diag**: os valores que são passados como parâmetro formam uma diagonal.

In [24]:
d = np.diag(np.array([1, 2, 3, 4]))

In [25]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
#Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [27]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [28]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [29]:
b

array([ True, False, False,  True])

In [30]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [31]:
s

array(['Python', 'R', 'Julia'], dtype='<U6')

**Linspace**

O método linspace (*linear spaced vector*) retorna um número de valores igualmente distribuídos em um intervalo especificado.

In [32]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [34]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

**logspace**: retorna valores log de um número de valores distribuídos 

In [35]:
np.logspace(0,5,10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])